### ISSUE TITLE
All APPS not show with Internet Explorer 11

### ISSUE THREAD

**Issue by Githopp192** [juliushaertl/apporder#52] opened 2017-10-12 12:31 UTC
AppOrder is working well with Microsoft Edge, with Chome and some other Browser .. 

but NOT WITH INTERNET EXPLORER 11.

The whole APP Column will disappear and many users are affected, which are not able to work anymore with their apps .. 

Support appreciated.

### General server configuration

**Operating system:** FreeBSD Nextcloud 11.0-RELEASE FreeBSD 11.0-STABLE #0 r321665+25fe8ba8d06(freenas/11.0-stable): Mon Sep 25 06:24:11 UTC 2017     root@gauntlet:/freenas-11-releng/freenas/_BE/objs/freenas-11-releng/freenas/_BE/os/sys/FreeNAS.amd64 amd64

**Web server:** Apache/2.4.27 (FreeBSD) OpenSSL/1.0.2j-freebsd PHP/7.0.21 (apache2handler)

**Database:** mysql 10.2.7

### Nextcloud configuration

**Nextcloud version:** 12.0.3 - 12.0.3.3

**PHP version:** 7.0.21

Cheers
Mike

**Comment by juliushaertl** [comment] 2017-10-13 11:57
duplicate of #51

**Closed by juliushaertl** 2017-10-13 11:57 UTC
