### ISSUE TITLE
Default landing page ignored

### ISSUE THREAD

**Issue by olantrust** [juliushaertl/apporder#54] opened 2017-11-22 12:32 UTC
Using Nextcloud 12.

Expected:
The first item in the list set under apporder settings, is the default landing page for that user.

Actual:
Nextcloud does not respect the default landing page set by apporder (i.e. the first in the list), and reverts to going to the Files app when a user logs in.

**Comment by juliushaertl** [comment] 2017-11-22 12:45
Have you set the default app config as required in the README?  https://github.com/juliushaertl/apporder#use-first-app-as-default-app

**Comment by juliushaertl** [comment] 2017-12-07 12:26
Cannot reproduce that, so I'm closing this, since it seems to be a missing configuration issue. Feel free to reopen if it still occurs.

**Closed by juliushaertl** 2017-12-07 12:26 UTC
