### ISSUE TITLE
App not working anymore with NC25

### ISSUE THREAD

**Issue by Synochy** [juliushaertl/apporder#114] opened 2022-10-24 06:35 UTC
Hello,

Since the NC25 update the app is not working anymore.
We can't choose the order or to activate or deactivate any app.

Thanks by advance for the fix.

**Comment by juliushaertl** [comment] 2022-10-24 06:41
duplicate of https://github.com/juliushaertl/apporder/issues/112#issuecomment-1251940348

**Closed by juliushaertl** 2022-10-24 06:41 UTC
